Servers:
  NameServer:
    - port: 5058
      external_address: 10.0.2.2:5058

  MasterServer:
    - port: 5055
      external_address: 10.0.2.2:5055

  GameServer:
    - port: 5056
      external_address: 10.0.2.2:5056

EnableIPv6: false
MaxConnections: 100
MaxGamePeers: 0
TickTimeBudget: 100000
